### ISSUE TITLE
Hollywooding the Gravity Vector Arrow

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/my-solar-system#104]
Creating this issue to discuss how are we going to display the gravity force, as the actual values can be overwhelmingly small or big... Any precedent either visually or in the codebase?

**Comment by jonathanolson** [comment]
I'm not aware of a precedent personally (there might be one). Perhaps we could use something proportional to the scale of the arrow (if we don't just lengthen the arrow, but widen it too?) That might look bad too.

I think we've just... kept the arrows accurate, and sometimes they can be very long or short? I'm aware of cases where if an arrow is very short, we just omit it visually.

**Comment by AgustinVallejo** [comment]
I dont mind really long arrows, what's problematic according to the interviews is that in some presets the arrows are literally invisible because of how small they are, so they can give the false impression of an absence of gravity, and we certainly don't want that.

**Comment by jonathanolson** [comment]
Perhaps we could have a visual indicator for "small, off-scale, but still there"? Like the arrow goes semi-transparent, with a dashed outline?

**Comment by AgustinVallejo** [comment]
I'm thinking that the arrow could shift in size between normal values 1 to 10 arbitrary units, and bigger or smaller it could have a x10^3 or x10^-5 indicator... we could either use Newtons as units or just arbitrary units in which I guess 5 could be the default state, to better see increases and decreases.

What do you think? @DianaTavares @arouinfar

**Comment by samreid** [comment]
During today's meeting, it seemed the +/- buttons could change the arrow scale and it worked ok to solve that problem. @AgustinVallejo said there is also supposed to be a message at the bottom of the screen. We also found it awkward that you cannot see what the scale is by looking, but @AgustinVallejo said the design team didn't want to add another number.  But maybe we can visualize the zoom level in another way?  But it is not a linear scale, and we don't want to accidentally convey that it is.

**Comment by DianaTavares** [comment]
I hope that with the “Scale” name in the control, they understand that the vectors are just scaling and not that the force is increasing or decreasing.  
An alternative is to add something like in waves, an arrow in the right upper corner of the play area when a force vector is active, showing the scale of the vector with a scientific notation, to include Newtons as the units: 
![image](https://user-images.githubusercontent.com/26031501/225474240-ec498455-f7fd-44e9-8522-62b8b5c9712c.png)

**Comment by AgustinVallejo** [comment]
I really like that suggestion!

**Comment by AgustinVallejo** [comment]
In today's design meeting it was decided that a slider should be used.

**Comment by zepumph** [comment]
From today's design meeting:

For the scale slider:
- [ ] Make tick mark for each "10 to the X"
- [ ] Have the min and max be tick mark labels (just those 2
- [ ] Support i18n for scale and labels


For the text: horizontally centered, in the bottom of the play area, like this:

![image](https://user-images.githubusercontent.com/6856943/225982720-dfb25ca3-3240-46e4-aa7c-eba3d9f3e7ab.png)

**Comment by arouinfar** [comment]
Here's what things currently look like in master normally and with `stringTest=long`
![Screenshot Capture - 2023-03-21 - 10-35-34](https://user-images.githubusercontent.com/8419308/226678633-b23e5bf2-9cf7-49e2-bfdc-af77ea612564.png)
![Screenshot Capture - 2023-03-21 - 10-35-27](https://user-images.githubusercontent.com/8419308/226678623-a53c3dc9-6a08-4f24-99f4-f480af1dd54f.png)

Here are the notes from discussion with @samreid @AgustinVallejo:
* The general slider strategy is good, and the layout has improved by moving the min/max labels to the tick marks.
* SR suggested we may need more cueing around the default value, especially since the thumb will snap there. We tried a variety of things.
   * Adding tick marks every order of magnitude with the same style as min/max ticks. This makes the values far more interpretable, and we liked this approach.
   * Adding tick marks every other order of magnitude. If the slider track gets shorter (and it likely will) this is a good alternative.
   * Making the 10^0 tick mark taller than the others. To make the tick style noticeably different, the minor tick marks end up very short.
   * Adding a `1` label to the 10^0 tick mark. It's a bit too close to the min label, and the slider track will likely get a bit shorter too.
   * Conclusion: At minimum, let's add tick marks every (or every other) order of magnitude, depending on how much horizontal space we end up with. Interviews will let us know if additional cueing is needed for the default value.
* The "Scale:" label looks very small. It is likely encountering its `maxWidth` and automatically shrinking. We would like to make more room for this label, and experimented with making the slider track shorter but did not have time to complete the pixel-polishing synchronously. 

Since our meeting, I've reviewed things a bit more:
* We should consider increasing the width of the panels to alleviate the crowding issues with the "Scale:" label. We already allow them to get wider with `stringTest=long`, so we have room. Can we try splitting the difference between the current default width and the panel `maxWidth`?
* I think we can slightly reduce the slider track size without compromising usability. This may not be necessary if widening the panel a bit allows prevents "Scale:" from reaching its `maxWidth`.
* Let's definitely add tick marks to the slider. If we don't have to reduce the track length, let's add ticks for each order of magnitude. If we do have to reduce the track width, every other order of magnitude will be fine.
* The placement of the "Some force vectors are off-scale." warning looks off. It also fails `stringTest=long` and is occluded by the panel. Let's center it horizontally in the play area as shown in the mockup in https://github.com/phetsims/my-solar-system/issues/104#issuecomment-1474211590. I think the string looks good at the top of the screen, so we can keep it there, just would like to see it properly centered.

**Comment by DianaTavares** [comment]
I had an interview today and I find this behavior strange:

- [ ] the text of "some forces vectors might be off scale" appears very soon for big vectors:

![image](https://user-images.githubusercontent.com/26031501/226760427-0442262f-5044-4dd1-ba2b-642e5b26fd60.png)

I think it needs to appear when the vectors get behind the panel or out of the view of the play area. In the example that I present, the vector goes out of the play area when it is moving (probably that is the reason of the text from the beginning). In that case, I recommend showing the text only when the vector is out, no matter that the text appears and disappears, but it is better that the user thinks that something is wrong with the vectors when he/she can see it, and the text appears. 
![image](https://user-images.githubusercontent.com/26031501/226760922-15412f07-b683-4c79-bd54-dae3b251602c.png)

- [ ] Conversely, the text does not appear when the vector is tiny. As soon as the vector is no longer visible, the text should appear.
![image](https://user-images.githubusercontent.com/26031501/226761245-61d1f6b6-d15a-4b84-a49d-94b02041351e.png)

**Comment by DianaTavares** [comment]
I also noticed in today's interview that the vectors, when they are huge, have a strange behavior. I took this screen shoot during the interview, where the vectors look fuzzy:

![image](https://user-images.githubusercontent.com/26031501/226777505-6dc647f8-d286-437c-b628-5ac16f3b7894.png)

I tried to reproduce that on my computer, but I couldn't, in place I get what is displayed in this video (hope you can appreciate them. I reduce the velocity of the video):

![vectors](https://user-images.githubusercontent.com/26031501/226777720-92076b6e-e49d-4429-9152-794dd1f87fa5.gif)

some vectors just appear and disappear, and also looks like broken close to the mass panel:
![image](https://user-images.githubusercontent.com/26031501/226777812-cfc4f5b2-e56d-43ba-9d59-a8fc44506699.png)
 
I know that vectors this size are not useful for the learning. If that is difficult to fix, I think that just by adding to the text that information, that is enough. “Some force vectors might be off-scale and with the velocity of reproduction they can look fuzzy”.

**Comment by AgustinVallejo** [comment]
We had a brief design meeting today!
- Threshold of the offscale warning message was adjusted
- The message itself was changed
- [ ] It was decided to center the [returnBodies,message] container between the control panel and the zoomButtons.

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo, the layout looks great in master!
