### ISSUE TITLE
Changing the DragListener in DraggableVectorNode

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/my-solar-system#107]
The code was obsolete

**Comment by zepumph** [comment]
- [ ] One thought I had was that DraggableVector2Property relies on a hard coded Property called `body.positionProperty`. @AgustinVallejo, could this instead be a parameter to the class like "vectorBasePositionProperty` or something?

**Comment by zepumph** [comment]
These commits addressed these review comments:

```
      // REVIEW: See if dragListener can be improved (with positionProperty)
      // REVIEW: NOTE that the transform for the DragListener needs to include the scale
     
```

**Comment by AgustinVallejo** [comment]
Thanks @zepumph, that's done!

**Comment by samreid** [comment]
CT said 

```
code: 2
stdout:
../../../solar-system-common/js/view/DraggableVectorNode.ts(138,29): error TS7006: Parameter 'modelViewTransform' implicitly has an 'any' type.

stderr:
```
So I pushed the fix above.

**Comment by zepumph** [comment]
Please assign me if you'd like me to review. Taking a look now.

**Comment by zepumph** [comment]
While reviewing, I bit the bullet and updated KeyboardDragListener to accept a Property for transform over in https://github.com/phetsims/scenery/issues/1547. It worked nicely! I also added a TODO attached to this issue because you can just use the Property for the transform. @AgustinVallejo will you clean that up please? Next I'll look at disposal.

**Comment by zepumph** [comment]
- [ ] dragDelta is more for single key presses, and for continuous movement, it is best to instead use dragVelocity which changes view coords per frame. I tried out some numbers, but please review and tweak the values as needed.
- [ ] There are grab/release sound clips for the planets, but not for the vector draggables. Is that purposeful? perhaps we should be consistent. Please ignore if this is a conscious decision.
- [ ] For the keyboard interaction, the sound clips should not be played on start/end, but instead on focus/blur events. This is buggy because start/end occurs for each key press. This sound is distracting and should be more for the "interaction". Try something like this:

```
Subject: [PATCH] use dragVelocity, https://github.com/phetsims/my-solar-system/issues/107
---
Index: js/view/BodyNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/view/BodyNode.ts b/js/view/BodyNode.ts
--- a/js/view/BodyNode.ts	(revision e1350d27c8ae65dfe14d2a8bdf738ff2cdbd1118)
+++ b/js/view/BodyNode.ts	(date 1678845281883)
@@ -179,6 +179,10 @@
           mapPosition: map
         } );
       this.addInputListener( keyboardDragListener );
+      this.addInputListener( {
+        focus: () => this.grabClip.play(),
+        blur: () => this.releaseClip.play()
+      } );
       this.disposeEmitter.addListener( () => {
         bodyDragListener.dispose();
         keyboardDragListener.dispose();
```

**Comment by zepumph** [comment]
Oops, my transpiler wasn't on so those drag velocities were way way off. Try that!
