### ISSUE TITLE
Update sounds for mass sliders

### ISSUE THREAD

**Issue by arouinfar** [phetsims/my-solar-system#136]
Discussed in today's sound meeting with @DianaTavares @jbphet @emily-phet @Ashton-Morris 

The Mass slider sound is based on an upright bass. The sound is very deep and rich and can compete with the acceleration sound (which should be the main focus).

We would like to try a lighter, more marimba-like sound for the Mass sliders. Additionally, we would like to differentiate the four sliders, similar to how we differentiate the acceleration sound for the four bodies.

@Ashton-Morris said he would iterate on the sounds and share video clips with some options.

**Comment by Ashton-Morris** [comment]
I have a few mockups op to listen to. 

I added text at the top of the Mockups with 4 different instruments because the video I am using only uses the top slider. So please use you imagination and imagine that I am adjusting all 4 sliders.


- [Mass Sliders Standard PhET Marimba Mockup.mp4](https://drive.google.com/file/d/1zdom58BX_VPUYnaP8j9FXh4oLz1IPL77/view?usp=share_link) - This is our tried and true basic PhET Marimba sound


- [Mass Sliders Same instruments with Pitch Mockup Text.mp4](https://drive.google.com/file/d/1usJhKwRGncxMFwRPNWSM81TsscXwu_TP/view?usp=share_link) - This uses **each actual mass sound** we currently use but shortened to be staccato and mapped to pitch

- [Mass Sliders Different Instruments Mallet Mockup Text.mp4](https://drive.google.com/file/d/1jyJucNea8ZeJ0dq1ht8NjZh-lnFqB54U/view?usp=share_link) - This uses different mallet instruments matched to pitch


Personally I feel that the PhET standard Marimba sounds nice as it usually does.  I also enjoy the mockup with the different mallet instruments, but I am not sure since they are different instruments than the bodies, if it will be confusing.

**Comment by arouinfar** [comment]
@Ashton-Morris @AgustinVallejo @DianaTavares @samreid @jonathanolson @KatieWoe @arouinfar reviewed the sound mockups today, and the consensus was that we preferred using the standard marimba for all four mass sliders. 

* Conceptually, there is no difference between the objects when they have the same mass. Using different sounds for each mass slider implies there is a difference. We also perceived a difference in pitch for like masses, which is problematic because we use pitch to indicate small vs. large values.
* We originally suggested using four different sounds for the mass sliders because we use four different sounds for the orbits. However, the objects move simultaneously, so it's necessary for each object to have a slightly different orbiting sound. Mass is adjusted individually and it should be clear to users (either from the description or visual changes) which object is being adjusted.
* The standard marimba sound is brighter than the current implementation and should address our previous concerns that it distracts from the orbiting sound (which is the most pedagogically important).

I think the next steps are for @AgustinVallejo and @Ashton-Morris to add the updated sound to the sim.

**Comment by AgustinVallejo** [comment]
Closing, as the chosen sound has been added.
