### ISSUE TITLE
Reset all button partially covered on iPad

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#155]
**Device**
iPad
**OS**
iOS 16
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/qa/issues/927.
On iPad, in landscape mode, the tool box on the right side of the second screen partially covers the reset all. I did not see this on Win 11 Chrome.
**Visuals**
![IMG_0002](https://user-images.githubusercontent.com/41024075/231888099-7e3ef6f1-5993-487b-9a27-43a0faa70c71.jpg)

**Comment by KatieWoe** [comment]
This also happens on portrait mode

**Comment by samreid** [comment]
I'll take a look

**Comment by samreid** [comment]
I reproduced the same problem on my iPhone and iPad. The cause may be due to a larger font size on iOS? Anyways, I tried correcting it by reducing margins and spacing like so:

<details>

```diff

Subject: [PATCH] Update to TypeScript 5.0.4, see https://github.com/phetsims/chipper/issues/1384
---
Index: main/solar-system-common/js/SolarSystemCommonConstants.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/solar-system-common/js/SolarSystemCommonConstants.ts b/main/solar-system-common/js/SolarSystemCommonConstants.ts
--- a/main/solar-system-common/js/SolarSystemCommonConstants.ts	(revision b5e8420d3a0ef0dff6cece0ad459fab5bd61ce03)
+++ b/main/solar-system-common/js/SolarSystemCommonConstants.ts	(date 1681433315269)
@@ -22,9 +22,9 @@
 
 const SolarSystemCommonConstants = {
 
-  MARGIN: 15,
-  SCREEN_VIEW_X_MARGIN: 15,
-  SCREEN_VIEW_Y_MARGIN: 15,
+  MARGIN: 10,
+  SCREEN_VIEW_X_MARGIN: 10,
+  SCREEN_VIEW_Y_MARGIN: 10,
 
   // Max width for many of the text labels
   TEXT_MAX_WIDTH: 200,
Index: main/my-solar-system/js/common/view/MySolarSystemScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/my-solar-system/js/common/view/MySolarSystemScreenView.ts b/main/my-solar-system/js/common/view/MySolarSystemScreenView.ts
--- a/main/my-solar-system/js/common/view/MySolarSystemScreenView.ts	(revision 5bea96427255e64f49985b96f81425adbefbb002)
+++ b/main/my-solar-system/js/common/view/MySolarSystemScreenView.ts	(date 1681433289727)
@@ -138,7 +138,7 @@
     } );
 
     this.topRightControlBox = new VBox( {
-      spacing: 10,
+      spacing: 7.5,
       stretch: true,
       children: [
         new Panel( new Node( { children: [ labModeComboBox ], visible: model.isLab } ), SolarSystemCommonConstants.CONTROL_PANEL_OPTIONS ),

```

</details>

![IMG_635C4F78B1DE-1](https://user-images.githubusercontent.com/679486/231913815-585a7fc1-e5a2-466e-843b-6e91de3f665e.jpeg)

This seems reasonable to me, but an alternative would be to reduce the text size for the control panel items slightly.  @AgustinVallejo or @DianaTavares or @arouinfar what do you recommend?

**Comment by DianaTavares** [comment]
Looks good! Also, reducing the text a bit will help not to see very tight the right panel. But, if we reduce the text, it needs to go in all panels. It is my opinion.

**Comment by samreid** [comment]
In design meeting, we discussed these topics:

* Should we reduce all iOS fonts to compensate? No, that would add too much complexity
* We tried reducing the font size from 16 to 15 but it didn't change the heights, probably due to the checkboxes being the limiting factor.
* We agreed the screenshot above looks good, so we will commit it and ask QA to double check.

**Comment by samreid** [comment]
Fixed, @KatieWoe can you please test on phettest? Close if ok.

**Comment by KatieWoe** [comment]
Looks good to me
