### ISSUE TITLE
Sound design sign-off

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/my-solar-system#163]
As per https://github.com/phetsims/my-solar-system/issues/131:
> publish a dev version and create a checklist of all of the sound designers and other stakeholders in the original sound design GitHub issue and ask them to either approve of the implementation or log their objections.

So I'm tagging most people involved in the sim, for you to take a listen to the newest dev version and its sound, please comment any suggestion or check your name if you approve.
[Dev version 1.1.0-dev.10](https://phet-dev.colorado.edu/html/my-solar-system/1.1.0-dev.10/phet/my-solar-system_all_phet.html)

- [ ] @kathy-phet
- [x] @emily-phet 
- [x] @Matthew-Moore240 
- [x] @Ashton-Morris  
- [x] @DianaTavares 
- [x] @arouinfar 
- [ ] @jonathanolson 
- [x] @samreid 
- [x] @AgustinVallejo 
- [ ] @jbphet 

Thanks!

**Comment by emily-phet** [comment]
@AgustinVallejo Sounds great - I hope you like how it all turned out. :) 
I did notice a bug unrelated to sound: when one of the bodies goes off screen, if you change the mass and then select "return", the one you changed the mass for does not display. If I selected a display change (like selecting and then de-selecting "path") the body suddenly reappeared. This seems like the body is still present in the model and its location is propagating in time, but it's not displayed consistently for some reason. This was easy for me to reproduce (Mac OS 13...something), so I didn't collect more details. Let me know if you can't reproduce it easily and I'll try to gather more details.

**Comment by AgustinVallejo** [comment]
@emily-phet thanks for the insight! After speaking with @arouinfar and @DianaTavares we decided to update the logic of the Return bodies to cover the case you're mentioning. See https://github.com/phetsims/my-solar-system/issues/147 for more details on the Return Bodies logic.

**Comment by arouinfar** [comment]
Overall, sounds good! I noticed that the measuring tape doesn't make any sound, which is a bit odd. I was expecting a pick-up sound similar to the other draggables. Was this an oversight or are there some other limitations @AgustinVallejo?

**Comment by samreid** [comment]
I tested it for 5 minutes or so, and it sounded really great!

**Comment by arouinfar** [comment]
@kathy-phet @jbphet @jonathanolson if you would like to provide feedback on the sound design, please do so by Thursday design meeting. Thanks!

**Comment by AgustinVallejo** [comment]
We demoed the latest sounds in yesterday's design meeting and everyone sounded happy with the outcome. :^)

Also @arouinfar says the measuring tape sound is good!
