### ISSUE TITLE
Possible to get "lose" a Body and not be able to retrieve it with the "Return Bodies" button

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/my-solar-system#165]
I was playing and I hit a combination of "Follow Center of Mass" after the body was off of the screen, and then hit "Return Bodies" it doesn't actually return the body to within the window view. I cannot get the body back in view using the Reset All button. 

Is "Return Bodies" always supposed to return it within the window view? 

I'm on -dev-10

**Comment by AgustinVallejo** [comment]
Hi, we discussed the 'Return bodies' logic in depth and left some notes in https://github.com/phetsims/my-solar-system/issues/147. Basically, it's really tricky because there will always be edge cases. Right now, 'Return bodies' works as a rewind button, same as in GaO. When you press 'Follow Center of Mass' you are creating a new saved state, so even though some bodies are still in the sim but out of the screen, 'Return Bodies' won't be able to bring them back.

**Comment by AgustinVallejo** [comment]
Action items:

- [ ] Follow center of mass should not save a new state.

**Comment by kathy-phet** [comment]
Sounds like a good discussion.
