### ISSUE TITLE
Change initial position of the sum and planet in the Kepler's Laws screen 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/my-solar-system#17]
Keppler's Law is more fun when the orbit is elliptical, and for that, the position of the objects needs to change. This is the look of the bodies in the mock-up:
![image](https://user-images.githubusercontent.com/26031501/187323508-eb028e29-95a6-4778-a8b7-c7f8d03009fb.png)

In the mockup the default values were:
Star’s velocity Vx= 0, Vy= 0
Star’s position x=-100 y=0 
Start’s mass = 250
Planet’s velocity Vx= 0 Vy= 50
Planet’s position  y=0
Planet’s mass = 0.01

Considering the center of the coordinates in the center of the play area.

**Comment by AgustinVallejo** [comment]
Are we sure we want this initial configuration? Because as soon as the user begins moving the planet, all orbits will be centered around the Sun, so they'll be off to the left!! 

What I propose is having the same orbit as the one in the picture but the Sun in the center of the screen, which is roughly in the other ellipse's focus. The planet can be to the other side (on Apoapsis) or in the same place (Periapsis). 

Let me know what you think, @DianaTavares

**Comment by DianaTavares** [comment]
We want that the initial shape of the orbit to be an ellipse, then yes, play with the positions to find one that best fits and generate more interaction from the users before generating something that goes beyond the play area.
