### ISSUE TITLE
Magic number in DraggableVelocityVectorNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#235]
In DraggableVectorNode, the magic number `1.3` should at the very least be documented. `new NumberProperty( 1.3 )` is the argument for param `forceScaleProperty`.

```ts
    super(
      body,
      transformProperty,
      visibleProperty,
      vectorProperty,
      new NumberProperty( 1.3 ),
      options
    );
```

**Comment by pixelzoom** [comment]
It's now in DraggableVelocityVectorNode, and looks like this:

```ts
    //TODO https://github.com/phetsims/my-solar-system/issues/235 why 1.3 ?
    const forceScaleProperty = new NumberProperty( 1.3 );
```

**Comment by AgustinVallejo** [comment]
This comment made me realize all the code regarding that force scale was needing a refactoring. In the above commits to the three repos I did the following:
- Rename `GravityZoomControl` to `GravityScaleControl`, since everywhere else the functionality was referred to as Scale. PD: This might change again in the future, currently discussing with @pixelzoom as it might all go back to 'Zoom'.
- Renamed `forceScaleProperty` to `forceScalePowerProperty` since it's the power of ten the vectors get scaled by.
- Changed the logic of the scaling so that `forceScalePower = 0` would not scale the vector. Previously this didn't happen because of initial states of the gravity vector, and that's why the magic number 1.3 was set in place incorrectly (Velocity vector shouldn't be scaled, and stating that its scale power was 1.3 was misleading)
- Cleaned up some commented out or irrelevant code.

Leaving open for possible future tweaks, one of which is adding an option so that velocity vector doesn't have to test it's magnitude for it being offscale, since velocity doesn't trigger the offscale message.

**Comment by pixelzoom** [comment]
Ugh... I renamed those from “scale” to “zoom” last week, to match the UI when I instrumented things. Now you’ve changed them back.  PhET-iO convention is that UI string, tandem name, and class name should all match (or be reasonably close) to make it easier to discover PhET-iO elements and related code. 

Now things are all over the place. For example in VisibilityControlPanel:

```ts
        // Gravity 'Zoom' control (labeled slider)
        new GravityScaleControl( model.forceScalePowerProperty, visibleProperties.gravityVisibleProperty,
          tandem.createTandem( 'gravityZoomControl' ) ),
```

**Comment by AgustinVallejo** [comment]
Noted! Will change back to zoom right away!

**Comment by pixelzoom** [comment]
`forceScalePowerProperty` seems fine, since it's in the model.

**Comment by AgustinVallejo** [comment]
Reverted the name change on the above commits
