### ISSUE TITLE
Discussion: Using 'Real Units' for the mass

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/my-solar-system#24]
There is the idea of being able to switch between **'Arbitrary Units'** and **'Real Units'** (The switch is already in place in the sim).

Real Units will use similar values as the ones seen in real astronomical systems, i.e. distances around 1AU, velocities of 30km/s, and periods in years (maybe days? undecided yet). Arbitrary Units will be the ones from the flash sim: distances of the order of 100 and velocities of around 50 (NO UNITS IN EITHER).

What @DianaTavares and I are having trouble in figuring out is the Masses, as the flash sim uses mases that range from 1 to 300, which do not correspond to usual planetary systems. Here's the proposal we have:

- Have Intro Screen use arbitrary units by default, and the masses range from 1 to 300.
- In Lab, only to use Real Units, the range goes from 0.001 earth Masses to 1'000.000 earth Masses.
- To make up for the hugely disproportionate range, in REAL UNITS, the Slider would work logarithmically: each slider step would control a power of ten: (0.001 - 0.01 - 0.1 - 1 - 10 - 100 ...) and if anybody wants a value in-between, they can click on the Number Display and type it in.
- Some of the presets masses would be shifted accordingly, so in examples like "Sun, planet and moon" the masses would reflect astronomical situations.

What do you guys think? @kathy-phet  @ariel-phet @arouinfar @matthew-blackman

**Comment by ariel-phet** [comment]
@AgustinVallejo this is likely a good discussion topic for a design meeting as I think there are several tradeoffs.

1. Logarithmic sliders are quite problematic, we tend to avoid that kind of UI component when possible, as it could be quite unexpected

2. If you really want to show a range that is that large, how are you going to depict the size of the object, I don't think we can easily display that big of a dynamic range (even if things are scaling with the cube of the radius)

3. Is it really that important that with the lab screen things scale like "usual planetary" systems? The universe is pretty immense and there are I believe lots of "supermassive" planets that have been found. Our Gravity and orbits sim covers the Sun/Earth system pretty well if someone is looking for something closer to our own solar system.

4. If you really desire this kind of range, perhaps consider a control where you perhaps you select from 4 ranges like "small planet, large planet, supermassive planet" and then the slider has a more linear range. Or perhaps even instead of a slider just have a set of buttons for selecting the mass and choose some distinct "real masses"

**Comment by arouinfar** [comment]
Based on yesterday's design meeting, I don't think my input is needed. Feel free to re-assign me if you have any further questions @AgustinVallejo

**Comment by DianaTavares** [comment]
I will close this issue. I am going to work in the mockup according to the stuff mentioned in status meeting: info button to show information about units in astronomy, and how the simulations are limited in the range of masses available.
