### ISSUE TITLE
followCenterOfMassButton still present after Reset All 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#274]
**Test device**
MacBook Air M1 chip

**Operating System**
14.0

**Browser**
Safari 17

**Problem description**
For https://github.com/phetsims/qa/issues/997 on the Lab screen, if you change the mass of a body and then press Reset All, the Follow Center of Mass Button doesn't disappear. This doesn't happen on the Intro screen. 

This isn't seen in 1.3.0-dev.1.

**Steps to reproduce**
1. Go to the Lab Screen and change the mass of either body using the slider or buttons
2. Press Reset All 

**Visuals**

https://github.com/phetsims/my-solar-system/assets/87318828/821e09d6-9075-43c2-9319-b97eec69c549

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-dev.3/phet/my-solar-system_all_phet.html
Version: 1.3.0-dev.3 2023-10-26 20:05:04 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15
Language: en-US
Window: 1410x711
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
Actually, if you just press Reset All without doing anything in the sim, the followCenterOfMassButton will appear.

**Comment by pixelzoom** [comment]
This has some overlap with https://github.com/phetsims/my-solar-system/issues/236, where I reported:

> 3. Press Restart button on time control. The bodies move to the correct "restart" positions. But the "Follow Center of Mass" button appears. Why?

The logic for when the "Follow Center of Mass" button appears seems to be generally buggy.

**Comment by pixelzoom** [comment]
Assigning to @Nancy-Salpepi and labeling as "ready-for-review".

**Comment by Nancy-Salpepi** [comment]
The Follow Center of Mass button in no longer present after pressing Reset All. 
However, it _should_ be present and isn't when I do the following:
1. On the Intro screen, move a body
2. Press Play
3. Press Restart

**Comment by pixelzoom** [comment]
I think we should start over on the implementation of visibility for `followCenterOfMassButton`.  It's way too complicated.  Ideally it should be a DerivedProperty, with dependencies something like this:

`[ this.availableBoundsProperty, this.modelViewTransformProperty, ...model.bodies.map( body => body.positionProperty ) ]`

**Comment by pixelzoom** [comment]
I think we should start over on the implementation of visibility for `followCenterOfMassButton`.  It's way too complicated.  Ideally it should be a DerivedProperty.  But I'm not sure what the dependencies are -- will need to discuss with @AgustinVallejo.

**Comment by pixelzoom** [comment]
@AgustinVallejo gave me a tutorial on the `followCenterOfMassButton`.   I think I have a better idea of how this feature works. But he is going to try to dig up the GitHub issue(s) where it was more fully described.

**Comment by AgustinVallejo** [comment]
I did some of the changes suggested in #236. Now, the followCenterOfMassButton appears based on model.followingCenterOfMassProperty, which derives from the CoM position (that it's within 1AU) and velocity (that it's smaller than 0.01km/s). This is way more reasonable and logical, and should be behaving as expected, instead of the previous way.

The only caveat is that now the Ellipses preset has that button on by default, since it's CoM is originally offset for the system to fit properly onscreen. We should discuss wether we wan't to:
a) Implement a cumbersome logic so that this specific preset doesn't trigger the property, at least until the user has interacted (pretty much what we had before).
b) Decide it's okay to have the button visible on the Ellipses system.
c) Decide to move the system a bit to the right

@arouinfar could you chime in on your thoughts on b) and c)?

**Comment by arouinfar** [comment]
@AgustinVallejo I like option (C). I moved the entire system over 1 AU to the right, and it looks reasonable to me.
![image](https://github.com/phetsims/my-solar-system/assets/8419308/6fc7cd7d-d8d3-455c-bd6f-f54da27c29ef)
![image](https://github.com/phetsims/my-solar-system/assets/8419308/cba938d5-692a-4efa-87a4-b4e6731fdea3)

**Comment by AgustinVallejo** [comment]
This is now ready to close.

**Comment by pixelzoom** [comment]
Reopening. Since `followCenterOfMasButton` has been a bit of a chronic problem, I think it would be a good idea to have @arouinfar (and perhaps @DianaTavares) review this issue, to verify that it's working as expected.

**Comment by pixelzoom** [comment]
Adding @Nancy-Salpepi too, since she created this issue.

**Comment by pixelzoom** [comment]
In an unrelated meeting, @arouinfar and @Nancy-Salpepi asked me to describe the behavior of the "Follow Center of Mass" button -- when it should and should not be visible -- so that they can verify in testing.  I had a difficult time doing this.   

@AgustinVallejo can you provide this description?

**Comment by pixelzoom** [comment]
@AgustinVallejo @arouinfar and I met about the behavior of the "Follow Center of Mass" button.

The visibility of the button is controlled by `followingCenterOfMassProperty` in MySolarSystemModel: 

```ts
    this.followingCenterOfMassProperty = new DerivedProperty(
      [ this.centerOfMass.positionProperty, this.centerOfMass.velocityProperty ],
      // we consider the center of mass is not being followed if it's outside the 1AU bounds or moving faster than 0.01 km/s
      ( position, velocity ) => position.magnitude < 1 && velocity.magnitude < 0.01
    );
```

Here's the button. Note that its visibleProperty is the `not` or `model.followingCenterOfMassProperty`:

```ts
    this.followCenterOfMassButton = new TextPushButton( MySolarSystemStrings.followCenterOfMassStringProperty, {
      visibleProperty: DerivedProperty.not( model.followingCenterOfMassProperty ),
```

So another way to put it is:  The button is visible when either of these 2 conditions occurs:
* the center of mass is >= 1 AU from the origin 
* the center of mass is moving at a speed of >= 0.01 km/s

@arouinfar @Nancy-Salpepi let us know if you need more info. Otherwise please proceed with testing.  The last one assigned please close this issue.

**Comment by pixelzoom** [comment]
@arouinfar @Nancy-Salpepi please hold off on testing. We found another problem.

To reproduce:
1. Got to Lab screen with "Sun, Planet" system selected
2. Check "Center of Mass" checkbox
3. Increase mass of body1 to 252.0, and the "Follow Center of Mass" button appears.
4. Press the "Follow Center of Mass" button, and it will immediately reappear.

Assigning to @AgustinVallejo to investigate.

**Comment by AgustinVallejo** [comment]
So this was a direct consequence of https://github.com/phetsims/my-solar-system/issues/278, which was closed but I'm rolling back a change in there and reopening, I'll describe more in depth the issue there.

With that rollback, this functionality is now back to it's desired state and ready to test.

**Comment by arouinfar** [comment]
The behavior on main looks good to me, but I think it would be good for @Nancy-Salpepi to also confirm.

**Comment by Nancy-Salpepi** [comment]
On the Lab screen, if an additional body is added, the Center of Mass button appears even though it doesn't look like the Center of Mass shifted at all. 
**This is also different behavior than what occurs in the published version. 
<img width="351" alt="Screenshot 2023-11-13 at 12 57 04 PM" src="https://github.com/phetsims/my-solar-system/assets/87318828/63183038-76f5-427a-8c0e-539e8f98c343">

**Comment by pixelzoom** [comment]
For the case that @Nancy-Salpepi reported in https://github.com/phetsims/my-solar-system/issues/274#issuecomment-1808714273, the center of mass is clearly NOT >= 1 AU from the origin.  Does it have velocity >= 0.01 km/s?  It's hard to tell, since the center of mass' velocity is not displayed anywhere.

**Comment by AgustinVallejo** [comment]
The Center of Mass is drifting in that example. Agree, it's hard to tell, I could notice it moved from the grid line after like 20 years running on 'fast', but it's there, so I think it's expected behavior. Adding a new mass with net velocity to a system will inevitably alter the center of mass of it.
![image](https://github.com/phetsims/my-solar-system/assets/37052186/b3a31f5a-9c00-4f4b-840c-bfaf1634abb7)

**Comment by pixelzoom** [comment]
I confirmed that adding a body causese the COM to moving at a speed >= 0.1 km/s.   I added this debugging output:

```diff
    this.followingCenterOfMassProperty = new DerivedProperty(
      [ this.centerOfMass.positionProperty, this.centerOfMass.velocityProperty ],
-      ( position, velocity ) => position.magnitude < 1 && velocity.magnitude < 0.01
-   );
+      ( position, velocity ) => {
+        const followingCenterOfMass = position.magnitude < 1 && velocity.magnitude < 0.01;
+        phet.log && phet.log( `followingCenterOfMass=${followingCenterOfMass} position.magnitude=${position.magnitude} velocity.magnitude=${velocity.magnitude}` );
+        return followingCenterOfMass;
 +     } );
  }
```

And the console output when adding a body is:

> followingCenterOfMass=false
> position.magnitude=0.18211559432936553
> velocity.magnitude=0.011517048346000884

**Comment by AgustinVallejo** [comment]
Even more interestingly, if you lower the velocity of that added body, at some point the button will disappear because it's now under the threshold. Again, this is expected behavior.

**Comment by pixelzoom** [comment]
This feature has been a chronic problem, and it has been difficult to understand/debug because COM Property values are not displayed in the sim.   So I've added the console output shown below.  When the sim is run with `&log`, any change to `followingCenterOfMassProperty` will be noted in the console, along with the values of its dependencies. 

```ts
    // Since followingCenterOfMassProperty was a bit of a chronic problem, this debugging output was added
    // for https://github.com/phetsims/my-solar-system/issues/274.  It prints the values of the dependencies
    // listed above.
    phet.log && this.followingCenterOfMassProperty.link( followingCenterOfMass => {
      phet.log && phet.log( `followingCenterOfMass=${followingCenterOfMass} ` +
                            `position.magnitude=${this.centerOfMass.positionProperty.value.magnitude} ` +
                            `velocity.magnitude=${this.centerOfMass.velocityProperty.value.magnitude}` );
    } );
```

**Comment by pixelzoom** [comment]
We've established that the behavior reported by @Nancy-Salpepi in https://github.com/phetsims/my-solar-system/issues/274#issuecomment-1808714273 is expected, there's nothing to do for that.

@Nancy-Salpepi anything else to report, or should we close this?

**Comment by Nancy-Salpepi** [comment]
Nothing else to report. Closing.
