### ISSUE TITLE
Add linked properties to view elements

### ISSUE THREAD

**Issue by arouinfar** [phetsims/my-solar-system#303]
For #295

View elements are generally linked to their corresponding properties. Overall, things are looking good in main, but I identified a few places where it would be helpful to add links:

- [x] Add link to `model.numberOfActiveBodiesProperty` under `view.numberOfBodiesControl`. 
- [x] Add link to `model.time.timeProperty` under `view.panels.timePanel.clockNode`.
- [x] Add link to `model.measuringTape` under `view.measuringTapeNode`.

**Comment by pixelzoom** [comment]
@AgustinVallejo will handle this one. Please assign to me for code review.

**Comment by AgustinVallejo** [comment]
Added the links, giving it back to @pixelzoom for review :)

**Comment by pixelzoom** [comment]
In the above commits, I made a couple of general changes.  

I'll `numberOfBodiesControl` as an example, but this is the way that @AgustinVallejo implemented the requests:

```ts
    this.numberOfBodiesControl = new NumberOfBodiesControl( model.numberOfActiveBodiesProperty, {
      visible: model.isLab,
      tandem: model.isLab ? options.tandem.createTandem( 'numberOfBodiesControl' ) : Tandem.OPT_OUT
    } );
    this.numberOfBodiesControl.addLinkedElement( model.numberOfActiveBodiesProperty, {
      tandemName: 'numberOfActiveBodiesProperty'
    } );
```

(1) When possible, it's preferrable to call `addLinkedElement` in the constructor of `NumberOfBodiesControl`.
(2) When calling `addLinkedElement`, you only need to provide `tandemName` if you want to use a name that is _different_ than the element's tandemName.

So in the above example, `this.numberOfBodiesControl.addLinkedElement` is replaced by this link added to the constructor of NumberOfBodiesControl:

```ts
    this.addLinkedElement( numberOfActiveBodiesProperty );
```

`measuringTapeNode.measuringTape` is the only case where the `addLinkedElement` call cannot be in the constructor, because MeasuringTapeNode is common code, and does not take `measuringTape` as an argument.  But the `addLinkedElement` call can be simplified by deleting the `tandemName` argument:

```ts
this.measuringTapeNode = new MeasuringTapeNode( measuringTapeUnitsProperty, {
   ...
} ;
this.measuringTapeNode.addLinkedElement( model.measuringTape );
```
 
@AgustinVallejo let me know if you have questions or want to discuss.   Assigning to @arouinfar to review, close if OK.

**Comment by arouinfar** [comment]
Thanks, I reviewed in main, and all the requested links were added. Some of the newly-added links aren't showing up in the featured tree, but we can address that in #304. Closing.
