### ISSUE TITLE
Return Bodies button appears when it shouldn't

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#325]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1015, in State wrapper the Return Bodies button can reappear if it had been pressed previously. 

**Steps to reproduce**
Here is an example:
1. In the State Wrapper, set state rate =0
2. In the upstream sim, go to the Lab Screen and select "hyperbolic" orbital system
3. Increase the mass of body 3 to 150
4. Press Set State Now
5. In the downstream sim, press Play
6. After bodies collide, press the Return Bodies button
7. Decrease the mass of body 3 to the minimum
8. Press the Follow Center of Mass button --Return Bodies button reappears

**Visuals**

https://github.com/phetsims/my-solar-system/assets/87318828/9fbb186d-d863-4c03-ad61-f5692ed1661b

**Comment by Nancy-Salpepi** [comment]
Actually, it happens in the sim too.

1. Select Hyperbolic on the Lab screen
2. Change mass of body 3 to 150
3. Press Play and wait for bodies to collide
4. Press Return bodies button
5. Change mass of body 3 back to minimum
6. Press Follow Center of Mass button

**Comment by AgustinVallejo** [comment]
This happens because when Following CoM in this system, a planet ends up beyond the draggable bounds: 
![image](https://github.com/phetsims/my-solar-system/assets/37052186/92e05b77-3fb4-46a1-ac68-af0d5c87f821)

Will try to change the initial position of it.

**Comment by AgustinVallejo** [comment]
By rotating the system 180° around the center I managed this configuration after Following CoM:

![image](https://github.com/phetsims/my-solar-system/assets/37052186/158bd8cf-fad0-4073-99bd-d8cf297f25d8)

It doesn't trigger the Return Bodies button.

It's also important to note that, for some systems, the "Return Bodies" might be triggered after the "Follow CoM", since the whole system moves, some planets might end up outside of the draggable bounds. This can also happen when zooming in, and in both those cases, because the "Return Bodies" button only rewinds the sim, it will not help nor do anything noticeable.

Because of the above, I'll ask @arouinfar opinion's on the change of initial conditions and if it's worth it. Otherwise we'd have to discuss about the possible uselessness of the Return Bodies button in some scenarios.

**Comment by arouinfar** [comment]
Good find @Nancy-Salpepi.

The behavior seems a bit odd, but it's also an edge case. In @Nancy-Salpepi's examples, she's not actually returning the body to its default mass. The minimum value reachable by the slider is 0.1 x 10<sup>28</sup>kg, but the default mass is something like 0.00001 x 10<sup>28</sup>kg. The configuration looks like the hyperbolic scenario, but it isn't an exact match.

I'm inclined to just do nothing here.
