### ISSUE TITLE
Mass changes when pressing Restart

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#328]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
FireFox/Chrome/Safari

**Problem description**
For https://github.com/phetsims/qa/issues/1015, if the mass of a body is changed with the increment/decrement buttons when the sim is playing, pressing Restart changes the mass value by 1. This is only seen if the button is pressed repeatedly --not seen if you press and hold or if you use the slider. 

EDIT: Actually the sim doesn't need to be playing initially for this to happen.

**Steps to reproduce**
1. On either screen press Play
2. Change the mass of body 1 by repeatedly pressing the increment button a few times
3. Press restart

**Visuals**

https://github.com/phetsims/my-solar-system/assets/87318828/ff2fe44b-3611-48ab-bfd0-53bbaf80037a

**Comment by AgustinVallejo** [comment]
This has popped up before in https://github.com/phetsims/my-solar-system/issues/171, going to investigate

**Comment by AgustinVallejo** [comment]
So, as far as I can tell, there are multiple things occurring here:
1. Might be related to https://github.com/phetsims/scenery-phet/issues/825: Apparently when the button has `fireOnDown: true`, the endCallback is being called before actually changing the numberProperty. This causes the state to be saved on M-1. This does not happen when `fireOnDown: true` or just when long-pressing the button.
2. We cannot bring back `fireOnDown: true` since it was causing https://github.com/phetsims/my-solar-system/issues/292

Might be a good one to pair as well @pixelzoom

**Comment by AgustinVallejo** [comment]
After talking with @pixelzoom it seems the potential error of NumberControl is not something we'd want to try to fix. Rather, I'll look into possible workarounds for this issue.

**Comment by AgustinVallejo** [comment]
Added a fix, please review and mark for cherry picking. Thanks!

**Comment by Nancy-Salpepi** [comment]
This looks good on main.

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.4
Closing.
