### ISSUE TITLE
PhET-iO: Ctrl+Hovering takes you to the view elements in the tree instead of the linked properties

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/my-solar-system#331]
Found by @Nancy-Salpepi, the sim is not behaving like other instrumented ones, where Ctrl+Hover should bring you to the linked element. Instead, in MSS it has the same behavior as Alt+Hovering. Some cases where this happens:

- [ ] Time control node
- [ ] The orbiting bodies
- [ ] Center of Mass X mark

The rest of components seem to be properly linking (checkboxes, Number Displays, etc etc). I feel like I need @pixelzoom insight as I'm not even sure how to start implementing this.

**Comment by Nancy-Salpepi** [comment]
linking to https://github.com/phetsims/qa/issues/1015

**Comment by Nancy-Salpepi** [comment]
Should Center Of Mass also be added to this list?

**Comment by pixelzoom** [comment]
Discussed with @AgustinVallejo and @arouinfar. This Studio feature only works when a PhET-iO element has a single linked element.   In the cases reported here, superclass ParallelDOM is adding linked elements for things like `visibleProperty` -- see `updateLinkedElementForProperty`.   So there's nothing we can do about this hotkey behavior, because it's a general "problem", known by the Studio developers.  I recommend we do nothing and close this issue.
