### ISSUE TITLE
Improvements to comparing data and number of bodies (legacy)

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/my-solar-system#4]
From unfuddle #2192

> I have a suggestion about "My Solar System" simulation.
> When i change number of bodies, their initial values also changes.
> But I'd like to - for example - make a system and see how it will behave, and then add another body to the system and see how its behavior will change. For now i must write my setting onto paper and then retype it into simulation.
> It is possible to make this simulation remember values, which i typed in?
> 
> I have also a small suggestion about maximum number of bodies - is it possible to add one (or more) additional body? I know, that number of calculations needed will increase greatly (is it O(n^2)?) but maybe 5 bodies isn't too much for computer?

**Comment by DianaTavares** [comment]
In the design meetings, we agree that is not necessary to change the number of max bodies in order to address the learning goals of the sim. The lab screen of the My Solar System has only the options of 2, 3, or 4 bodies.  

about the first part of the issue:
> When i change number of bodies, their initial values also changes. But I'd like to - for example - make a system and see how it will behave, and then add another body to the system and see how its behavior will change.....It is possible to make this simulation remember values, which i typed in?

In the Flash-version of the simulation, when the user modifies the number of bodies, all the bodies in the play area change to a specific preset:
![image](https://user-images.githubusercontent.com/26031501/111516002-0f909d80-8719-11eb-80b8-5f403c383f46.png)
![image](https://user-images.githubusercontent.com/26031501/111516032-161f1500-8719-11eb-8e85-523f20435069.png)

I wonder if it's possible for the simulation to have a similar behavior that Collision lab, where user can modify (by adding or subtracting) bodies on the play area, and this just update the behavior in the movement of the rest of the bodies:

3 bodies in the play area:
![image](https://user-images.githubusercontent.com/26031501/111516762-e290ba80-8719-11eb-84bc-a8708ccbf558.png)

When the user adds a 4 body, the initial values of the rest of the bodies is conserved: 
![image](https://user-images.githubusercontent.com/26031501/111516836-005e1f80-871a-11eb-9661-ab21dc98a60f.png)


In the same way, if one of the bodies is deleted, the other bodies conserve their initial values:
![image](https://user-images.githubusercontent.com/26031501/111516907-179d0d00-871a-11eb-87fd-69a563c3e74b.png)

@solaolateju commented that this is harder in My Solar System (MSS) for 1)the role of of the gravity in the movement of the objects (add/delete a body in the play area effect immediately the motion of the other bodies, and this is different from collision lab where the movement of the bodies only is affected when the bodies get in contact), and 2)MSS simulation has a lot of presets.

@solaolateju is going to describe more in this issue about the options and questions related to this.

**Comment by DianaTavares** [comment]
We include this issuer suggestion in the new design! Clossing this issue.
