### ISSUE TITLE
Suggestion for save/load (legacy)

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/my-solar-system#5]
From Unfuddle #3523

> We’ve been using “My Solar System” recently and found that it would be convenient to be able to “save” a group of settings (as has been done for the various presets).  I have particular combinations I like to show my classes and they also enjoy coming up with their own, but it is inconvenient to have to type in each value each time.  Would you consider adding a button to save the settings to a local computer, then load in any preset group of settings as desired?  This would be greatly appreciated.  Thank you for your consideration.  Keep up the good work!

**Comment by ariel-phet** [comment]
Perhaps this goal could be addressed with a greater number of pedagogically useful presets (we could reach out to the user for the combinations then tend to use).

Save and load is also something we have considered addressing in several simulations. Perhaps a query parameter set could solve this problem as well for initial conditions.

**Comment by DianaTavares** [comment]
in a discussion with @arouinfar over slack, we agree that this is not a practical functionality for MSS. Also, with the controls to modify the initial values of the bodies in the lab screen, set a specific custom option there is faster and more practical than with query parameters because the number of bodies and initial values is big.
