### ISSUE TITLE
Gravity arrows missing in screenshot

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#52]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.0.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/860, the Gravity arrows are missing from screenshots.

**Visuals**
The top pic is the sim and the bottom is the screenshot. 

<img width="532" alt="Screenshot 2022-11-30 at 2 36 33 PM" src="https://user-images.githubusercontent.com/87318828/204892533-0e410b7c-d485-433a-bc37-1b4e8e8958ee.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.0.0-dev.7/phet/my-solar-system_all_phet.html
Version: 1.0.0-dev.7 2022-11-29 20:47:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1564x732
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
I saw something similar in https://github.com/phetsims/gravity-and-orbits/issues/426 if that is helpful to you.

**Comment by AgustinVallejo** [comment]
Design decision: Won't be fixed for Prototype!

**Comment by Nancy-Salpepi** [comment]
@AgustinVallejo I'm going to change this priority to 3 if that is OK? It is something that should be fixed for the non-prototype version.

**Comment by AgustinVallejo** [comment]
This is still happening!

**Comment by AgustinVallejo** [comment]
@zepumph will take a look into this, thanks!

**Comment by zepumph** [comment]
This is because you have `boundsMethod: 'none',` in VectorNode. I am not sure why we need that, but my first thought would be to try to update that. Otherwise I would ask JO why that excluded a Node from rasterization.

**Comment by zepumph** [comment]
@jonathanolson and I talked about this just now, and he taught me about how boundsMethod: 'none' is buggy unless it is specified with a custom override of the localBounds. Otherwise you are just telling scenery that you don't take any valid bounds, and scenery is allowed (and potentially expected) to not display your content. Just because the screenshot is the only spot where this occurs doesn't mean that it will be in the future.

Instead, fix this with a localBounds setter that encapsulates your node in bounds, but in a much more performant way. 

@AgustinVallejo please review.

**Comment by AgustinVallejo** [comment]
Looks good!
